"""Users ga user avatar qo'shildi

Revision ID: 824a9ee0f1fb
Revises: 7f68cfef8d7c
Create Date: 2026-05-03 20:07:29.670477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '824a9ee0f1fb'
down_revision: Union[str, Sequence[str], None] = '7f68cfef8d7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_avatar', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_avatar')
    # ### end Alembic commands ###
